// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.MainWindowViewModelTests.MainWindowViewModel_AddItemCommand_ReturnsCorrectCount")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.MainWindowViewModelTests.MainWindowViewModel_CreateItemCommand_ReturnsCorrectCount")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.MainWindowViewModelTests.MainWindowViewModel_AddNullCommand_ReturnsCorrectCount")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.MainWindowViewModelTests.MainWindowViewModel_RemoveItemCommand_ReturnsCorrectCount")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.MainWindowViewModelTests.MainWindowViewModel_RemoveNullCommand_ReturnsCorrectCount")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.ShoppingItemVisibleConverterTests.ShoppingItemVisibleConverter_ShoppingItem_ReturnsVisible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.ShoppingItemVisibleConverterTests.ShoppingItemVisibleConverter_String_ReturnsHidden")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.ShoppingItemVisibleConverterTests.ShoppingItemVisibleConverter_Null_ReturnsHidden")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:ShoppingList.Tests.ShoppingListTests.ShoppingList_Constructor_ReturnsCorrectName")]
