// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.FileConfig_NoFileGetConfigByName_ReturnsNull(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.FileConfig_SetConfigValue_GetReturnsCorrectValue(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.FileConfig_SetBadNameOrValue_ThrowException(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:Configuration.Tests.MockConfigTests.MockConfig_SetConfigValue_GetReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.EnvironmentConfig_SetConfigValue_GetReturnsCorrectValue(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.EnvironmentConfig_SetBadNameOrValue_ThrowException(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test Methods should contain underscores", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.EnvironmentConfig_SetBadNameOrValue_ReturnsFalse(System.String,System.String)")]
